---
# tasks file for terraform

- name: Downloading archive for {{ terraform_app }} {{ terraform_version }} temporarily to {{ terraform_dl_loc }} on EL based systems
  get_url:
    url: "{{ terraform_dl_url }}/{{ terraform_app }}/{{ terraform_version }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    dest: "{{ terraform_dl_loc }}"
# - name: Gather package facts to verify if unzip is installed on EL based systems
#   package_facts:
#     manager: rpm
- name: Install unzip if it is currently not in an installed state on EL based systems.
  yum:
    name: unzip
    state: present
    update_cache: yes
  # when: packages['unzip'] is not defined
- name: "Extract {{ terraform_app }} archive on EL based systems"
  unarchive:
    src: "{{ terraform_dl_loc }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    dest: "{{ terraform_bin_path }}"
    remote_src: true
- name: Uninstalling unzip from Debian based systems as it was originally not in installed state on EL based systems.
  yum:
    name: unzip
    state: absent
  when: packages['unzip'] is not defined
- name: "{{ terraform_app }}_archive_removal on EL based systems"
  file:
    path: "{{ terraform_dl_loc }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    state: absent
