---
# tasks file for terraform | EL Family

- name: EL Family | Downloading archive for {{ terraform_app }} {{ terraform_version }} temporarily to {{ terraform_dl_loc }}
  get_url:
    url: "{{ terraform_dl_url }}/{{ terraform_app }}/{{ terraform_version }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    dest: "{{ terraform_dl_loc }}"

# - name: Gather package facts to verify if unzip is installed on EL based systems
#   package_facts:
#     manager: rpm

- name: EL Family | Install unzip if it is currently not in an installed state
  yum:
    name: unzip
    state: present
    update_cache: yes
    # when: packages['unzip'] is not defined

- name: EL Family | Extract {{ terraform_app }} archive
  unarchive:
    src: "{{ terraform_dl_loc }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    dest: "{{ terraform_bin_path }}"
    remote_src: true

- name: EL Family | {{ terraform_app }}_archive_removal
  file:
    path: "{{ terraform_dl_loc }}/{{ terraform_app }}_{{ terraform_version }}_{{ terraform_osarch }}.zip"
    state: absent
